### PR TITLE
added snap support

### PR DESCRIPTION
**Pull request by tuxfy**
maybe it's useful to combinate it with apt/dnf -> apt/dnf/snap

### CODE REVIEW

**Comment by tuxfy** [comment]
> Also, I would suggest creating pull requests against `v3` instead of `master`. That would help testing things out and managing releases.

Ok. no problem :)

**Comment by tuxfy** [comment]
> Thanks @tuxfy
> This is helpful but seems redundant.
> It would be even better if we could model it the way `shellrc.sh` works with `bash-zsh.sh`.
> Something like `systemctl-service.sh` and `snapd.sh`, `dockerd.sh`.

sounds logical

**Comment by himanshub16** [comment]
Sorry for late reply. Got caught up in exams. Shall review and merge next week.

**Comment by tuxfy** [comment]
No problem. Here is an updated version.
https://github.com/tuxfy/ProxyMan/blob/master/dists/snap.sh
Added missing touch command for initial creating the conf file

**Pull request closed without merging**
