### PR TITLE
added environment.sh

### PR DESCRIPTION
**Pull request by tuxfy**

### CODE REVIEW

**Comment by himanshub16** [comment]
Yes. That was intentional, but having the same content here causes redundant code.

So yeah, it would be better if we can have an entry (intentionally commented out) in `bash-zsh.sh` or a file `environment.sh` with the same content as `bash-zsh`.

**Comment by tuxfy** [comment]
Maybe something like this

1. do_all without environment
2. do_all with environment (REBOOT REQUIRED)
3. terminal
4. ....
5. environment (REBOOT REQUIRED)

**Comment by himanshub16** [comment]
Okay. But why would one need proxy settings in `/etc/environment`?
Wouldn't `Default env_keep += "http_proxy"` in `/etc/sudoers` work?

The hesitation behind using `/etc/environment` is the requirement of log-out required to reload it.

**Comment by tuxfy** [comment]
For example:
https://forum.snapcraft.io/t/set-snapd-proxy-via-core-configuration/467/20
But, I testing the alternative way /etc/systemd/system/snapd.service.d/proxy.conf

**Pull request closed without merging**
