### PR TITLE
Restore and adapt environment.sh script

### PR DESCRIPTION
**Pull request by danielemegna**
Restore and adapt environment.sh script. This close issue #78.
______

This pull request has been developed during [Open Source Saturday #28](https://www.meetup.com/it-IT/Open-Source-Saturday-Milano/events/264311424/) meetup in Milan. 

[Open Source
Saturday](https://www.meetup.com/it-IT/Open-Source-Saturday-Milano/)

### CODE REVIEW

**Comment by himanshub16** [comment]
Thanks a lot @danielemegna 
This works. But we could rather try using `bash-zsh.sh` which in-turn calls `shellrc.sh`.
That reduces the amount of code to maintain.

**Comment by danielemegna** [comment]
> Thanks a lot @danielemegna
> This works. But we could rather try using `bash-zsh.sh` which in-turn calls `shellrc.sh`.
> That'll also require `main.sh` to be updated to call `bash-zsh.sh` with `sudo` privilege.
> That reduces the amount of code to maintain.

I agree. But I thought that the priority was to quickly restore a working version :)
Currently a bad massage is shown and a core functionality is missing.

**Comment by danielemegna** [comment]
hey @himanshub16 , can we evaluate this hotfix? the current version does not work :(

**Comment by himanshub16** [comment]
Made a fix in #94 
Let me know if it helps.

**Comment by danielemegna** [comment]
> Made a fix in #94
> Let me know if it there's any issue.

Seems to work!

**Pull request closed without merging**
