### PR TITLE
Change protocol https to http for 'https proxy'

### PR DESCRIPTION
**Pull request by saburto**

### CODE REVIEW

**Comment by himanshub16** [comment]
I appreciate it. But why is this change required?

**Comment by saburto** [comment]
Quick answer is in this bug: https://github.com/himanshub16/ProxyMan/issues/41

For my experience the proxys server that I have to deal with only use the http protocol with a custom port. For example with cntlm o px tool you open a proxy like http://127.0.0.1:3128, no https.

The https_proxy configuration works fine with an http proxy server.
Example:

**http**s_proxy=**http**;//127.0.0.1:3128

Maybe the selection of https for proxy protocol could be a new option on main script.

**Comment by himanshub16** [comment]
Well, I never heard anyone running into an issue with `https`, apart from `npm` (which is referenced in #41 ). 
I shall keep this to another branch unless there are more people running into problems or we get sure if this really solves one.

**Comment by himanshub16** [comment]
Thanks @saburto  . Found that few more people were running into the similar problem as in #41 .

Merging this. 😄

**Comment by saburto** [comment]
:+1: good

**Comment by max-te** [comment]
This breaks support for my universities proxy server. They only proxy https connections if the proxy is accessed via https.

**Pull request merged**
